services:
  banco_loja:
    image: postgres:16-alpine
    container_name: aromas_regalos_postgres
    environment:
      POSTGRES_DB: Aromas-y-Regallos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dados_postgres_aromas:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Aromas-y-Regallos"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  dados_postgres_aromas:
